[2018-09-13 16:56:15,368 - log.py] - ERROR : MetadataCityIncrementAssertError
[2018-09-13 16:56:15,368 - log.py] - ERROR : http://192.168.100.34:8889/business/metadata/city/increment
[2018-09-13 16:56:15,368 - log.py] - ERROR : get
[2018-09-13 16:56:15,368 - log.py] - ERROR : {'Content-Type': 'application/json', 'Route_Api_Auth_Heard': "{'apiKey':'${apiKey}'}", 'Hyaline-Auth-AccessHeader': "{'sysCode':'${sysCode}','bizCode':'${bizCode}','sign':'03559e3e74efc9f60b6abd7d55c9df60','timeStamp':'12312'}"}
[2018-09-13 16:56:15,368 - log.py] - ERROR : {'lastQueryTime': '1310665474004'}
[2018-09-13 16:56:15,369 - log.py] - ERROR : 接口测试断言错误
[2018-09-13 16:56:15,369 - log.py] - ERROR : 10002等于12
[2018-09-13 16:56:15,391 - log.py] - ERROR : MetadataCityIncrementAssertError
[2018-09-13 16:56:15,391 - log.py] - ERROR : http://192.168.100.34:8889/business/metadata/city/increment
[2018-09-13 16:56:15,392 - log.py] - ERROR : get
[2018-09-13 16:56:15,392 - log.py] - ERROR : {'Content-Type': 'application/json', 'Route_Api_Auth_Heard': "{'apiKey':'${apiKey}'}", 'Hyaline-Auth-AccessHeader': "{'sysCode':'${sysCode}','bizCode':'${bizCode}','sign':'03559e3e74efc9f60b6abd7d55c9df60','timeStamp':'12312'}"}
[2018-09-13 16:56:15,392 - log.py] - ERROR : {'lastQueryTime': '1310665474004'}
[2018-09-13 16:56:15,392 - log.py] - ERROR : 接口测试断言错误
[2018-09-13 16:56:15,392 - log.py] - ERROR : 10002等于12
